### ISSUE TITLE
find Scheme not working

### ISSUE THREAD

**Issue by TechGuyVN** [sodascourse/hw-test-loader#1]
Hi,

Im using function Scheme.find_scheme but it not return any scheme
please take a look

**Comment by sodastsai** [comment]
well, is your scheme marked as a shared one?
Also this is just a side project of mine. Since I'm quite busy with my full-time job, it would be great if you submit a PR to fix for any issue you found.

**Comment by TechGuyVN** [comment]
THanks for answer my question, i has solved my problem, your script wrong with mine because my schema not in workspace folder, you script hard code it :).
My schema placed in xcuserdata, so i modify your script like this and it working:

> pattern_path = File.join source_path, 'xcuserdata'
>     # puts pattern_path
>     result = ''
>     xcscheme_paths = []
>     Find.find(source_path) do |path|
>     xcscheme_paths << path if path =~ /.*.xcscheme$/
>     end

**Comment by sodastsai** [comment]
sure, but for scripts running on where don't really open Xcode, like CI server, only schemes puts under `xcshareddata` are available.
